name: SBOM + Scan

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  sbom-and-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Syft
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh
          sudo install ./bin/syft /usr/local/bin/syft
          syft version

      - name: Generate SBOM (Table)
        run: |
          syft dir:. -o table > sbom.txt

      - name: Generate SBOM (CycloneDX JSON)
        run: |
          syft dir:. -o cyclonedx-json > sbom.json

      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget -qO trivy.deb https://github.com/aquasecurity/trivy/releases/latest/download/trivy_0.50.0_Linux-64bit.deb
          sudo dpkg -i trivy.deb
          trivy --version

      - name: Scan SBOM with Trivy
        run: |
          trivy sbom sbom.json -f json -o results.json

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sbom-and-results
          path: |
            sbom.txt
            sbom.json
            results.json
